language: cpp
sudo: false
common_sources: &1
- ubuntu-toolchain-r-test
- llvm-toolchain-trusty
matrix:
  include:
  - env: COMPILER='/Users/travis/build/andreasfertig/travistest/clang/current/bin/clang++'
      COMPILER_CC='/Users/travis/build/andreasfertig/travistest/clang/current/bin/clang'
      LLVM_CONFIG='/Users/travis/build/andreasfertig/travistest/clang/current/bin/llvm-config'
    os: osx
    osx_image: xcode9.3
    compiler: clang
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: *1
        packages:
        - clang-7
        - libstdc++-6-dev
        - llvm-7-dev
        - libclang-7-dev
        - zlib1g-dev
    env: COMPILER='clang++-7' COMPILER_CC='clang-7' LLVM_CONFIG='/usr/bin/llvm-config-7'
      DEPLOY="Yes"
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: *1
        packages:
        - g++-8
        - clang-7
        - libstdc++-6-dev
        - llvm-7-dev
        - libclang-7-dev
        - zlib1g-dev
    env: COMPILER='g++-8' COMPILER_CC='gcc-8' LLVM_CONFIG='/usr/bin/llvm-config-7'
install:
- "${TRAVIS_BUILD_DIR}/scripts/travis_install.sh"
before_script:
- export CXX=${COMPILER}
- export CC=${COMPILER_CC}
- env
- echo $CXX
- cd "${TRAVIS_BUILD_DIR}"
- mkdir build
- cd build
- cmake -DINSIGHT_LLVM_CONFIG=${LLVM_CONFIG} ..
script:
- export TAG_NAME=$(git describe --exact-match)
- make -j VERBOSE=1
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]] && [[ -n $TAG_NAME ]]; then
      export GZ_FILE_NAME=${TRAVIS_BUILD_DIR}/insights-macos.tar.gz
  fi
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ -n $TAG_NAME ]]; then
      export GZ_FILE_NAME=${TRAVIS_BUILD_DIR}/insights-ubuntu-14.04.tar.gz
  fi
- tar -czf ${GZ_FILE_NAME} ${TRAVIS_BUILD_DIR}/build/travistest

after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- |
  if [[ -n $TAG_NAME ]]; then
      bash upload.sh ${GZ_FILE_NAME}
  fi
env:
  global:
  - secure: QnFBjBWMyn6A9Cs+cf8tDNyVmQkbig3YW6IfJcjsXQ57hMNTqrKOyvUMNAIxyxDL3sh5HrBAkeaVRI0uiGOwCQaigBg4tMEdjTZfiH9pNjKpbZli8OUB3I0LPMSmYkIZRQiN/A5BsuyFpXMCwMgg0wwSc8HgjZBuzBXMSlC26O8rXD62ZTT7ZKYGovOW5GX7UuxUTZ4UvUUycMajZjteuYQgnsXI8aNQaWO8pV7wuI2+ayHKvKVS6OSBzrlXkb74GIK37ltSjbNJbS31mpdd81NfJE7HQK9Kfqwrsr852uTEbeiZoe6sOT0CajaPpmkEUjR/WrCptXZuvtpNppQLQSTLLJXVRoUM8PyGAbtWGU+fTz4wFcvJgEBWKlwpSEqVr8KvPs4GzAJi4RfG8Q2Lwd86Xtdu/1S8mHJ5xTGO3FNw6xvrM5JVCg8g7rfrJGrBF8vCY+XE/YJKpXly3ZoPPPGx0lAyElvBveMQnyaMYvdI1BAGoosrKOAUPDDzUqptwWKb/g/DgUVyKS0srK12x9baFep7Vk693jcpAKmt5EKewFBcbJKdIlWWrp+5ZJvbOCeWjdn4DPc0WPNha+Mz5ahaCUm2AWml9a1KEAj0ApqD0UsrysNjzw0EloRwapTMXnWVwcMIF9ZFcmf7xkPfgl1qvYbJ6E9xxwEYnifAWNw=
  - secure: U9D3UKGgFtXcOeijwEaBixTs27K4ij8c4+duHIg2Kx4onT3yB+iJW8gPw7w9cg9P+HXeCcA9+kV+rR+v2L7wkxn18UFnrHDYu+pvIu52/wQ2h85GWj3z29TYFH0Kttom3XpeX0VzEGmL8irntvJyrwbWtVxjougIe0LUXZyv51gjsg4FvPRzUqh/9aJhuS6+3dRWuT03JoZ1Cw8bSX22KqeUT4tLz13HZDHfmNd5lGANTG1NDQUhUkDY/ydsWnIUeyJ0jtNroECsXocc7b/8nR3GSJWnrttflY60vMYClXwoiA3sBzYzTNXUw8Tc+TRQN/g3lmnLt2J0Y+m13rRClhyaAnCzazZO1GI4sL9pHASYVHlPAnFlTmyaW0U6j0STIwcl4uqfpT8cIIKEusgtFI59xJWTe/Rpgdxf7vui22cutBhjkgwCVHZPJiEVyUZgWSZWxivkt5eEpeRTOcXYZ4MrMaiN36aEKA8HKGETs1DtoLvrv1kaQ7IL3iNwD0QZZnRmka/PRY4h0jh22qfDrYhxD/mJvaEqYIfF/WXUl2TDGpSSIv+AIiiMTxcKvS11RMSbP6ueLXOUyEzhv7WqHow4kVGcoMnSlGFKOdMZr83G3xWnZZBLiI4Tsw2HIA1YMu72ISxPzR8jzmla+T4PKl4rTQkYhDYlP9eQOZ6GeCw=
