language: cpp
sudo: false

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty

matrix:
  include:

    - env: COMPILER='${TRAVIS_BUILD_DIR}/clang/current/bin/clang++' COMPILER_CC='${TRAVIS_BUILD_DIR}/clang/current/bin/clang' LLVM_CONFIG='${TRAVIS_BUILD_DIR}/clang/current/bin/llvm-config'
      os: osx
      osx_image: xcode9.3
      compiler: clang
      
    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-7', 'libstdc++-6-dev', 'llvm-7-dev', 'libclang-7-dev', 'zlib1g-dev']
      env: COMPILER='clang++-7' COMPILER_CC='clang-7' LLVM_CONFIG='/usr/bin/llvm-config-7'

    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: ['g++-8', 'clang-7', 'libstdc++-6-dev', 'llvm-7-dev', 'libclang-7-dev', 'zlib1g-dev']
      env: COMPILER='g++-8' COMPILER_CC='gcc-8' LLVM_CONFIG='/usr/bin/llvm-config-7'

      
install:
  - ${TRAVIS_BUILD_DIR}/scripts/travis_install.sh

before_script:
  - export CXX=`echo ${COMPILER}`
  - export CC=`echo ${COMPILER_CC}`
  - env
  - echo $CXX
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build
  - cd build
  - cmake -DINSIGHT_LLVM_CONFIG=`echo ${LLVM_CONFIG}` ..

script:
  - make -j VERBOSE=1
