language: cpp
sudo: false
dist: bionic


cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/clang-windows
common_sources: &1
- ubuntu-toolchain-r-test
- llvm-toolchain-trusty
matrix:
  include:
  - env: COMPILER='/Users/travis/build/andreasfertig/travistest/clang/current/bin/clang++'
      COMPILER_CC='/Users/travis/build/andreasfertig/travistest/clang/current/bin/clang'
      LLVM_CONFIG='/Users/travis/build/andreasfertig/travistest/clang/current/bin/llvm-config'
    os: osx
    osx_image: xcode9.3
    compiler: clang
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: *1
        packages:
        - clang-7
        - libstdc++-6-dev
        - llvm-7-dev
        - libclang-7-dev
        - zlib1g-dev
    env: COMPILER='clang++-7' COMPILER_CC='clang-7' LLVM_CONFIG='/usr/bin/llvm-config-7' DEPLOY="Yes"
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: *1
        packages:
        - g++-8
        - clang-7
        - libstdc++-6-dev
        - llvm-7-dev
        - libclang-7-dev
        - zlib1g-dev
    env: COMPILER='g++-8' COMPILER_CC='gcc-8' LLVM_CONFIG='/usr/bin/llvm-config-7'
  - os: windows
    env: COMPILER='g++-8' COMPILER_CC='gcc-8' LLVM_CONFIG='/usr/bin/llvm-config-10'
install:
- "${TRAVIS_BUILD_DIR}/scripts/travis_install.sh"
- |   
  if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
    mkdir -p ${TRAVIS_BUILD_DIR}/clang-windows
    cd ${TRAVIS_BUILD_DIR}/clang-windows
    #    wget -q --continue --directory-prefix=$HOME/Library/Caches/Homebrew https://github.com/andreasfertig/cppinsights-compiler-binaries/releases/download/8.0.0/llvm+clang-8.0.0-win64-msvc-release.tar.xz
    wget -q --continue https://github.com/andreasfertig/cppinsights-compiler-binaries/releases/download/10.0.0/llvm+clang-10.0.0-win64-msvc-release.tar.xz
    mv llvm+clang-10.0.0-win64-msvc-release.tar.xz llvm.tar.xz
    ls -l
    7z x ${TRAVIS_BUILD_DIR}//clang-windows//llvm.tar.xz
    7z x ${TRAVIS_BUILD_DIR}//clang-windows//llvm.tar
    rm -f llvm.tar    
    ls -l llvm+clang-10.0.0-win64-msvc-release/bin
    export "PATH=${TRAVIS_BUILD_DIR}/clang-windows/llvm+clang-10.0.0-win64-msvc-release/bin;$PATH"
    #mkdir -p ${TRAVIS_BUILD_DIR}/vs2019
    choco install visualstudio2019community
    choco install visualstudio2019buildtools
    # --params "/InstallDir:${TRAVIS_BUILD_DIR}/vs2019"
    ls -lR /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Community
    vswhere
  fi
before_script:
- export CXX=${COMPILER}
- export CC=${COMPILER_CC}
- env
- echo $CXX
- cd "${TRAVIS_BUILD_DIR}"
- mkdir build
- cd build
- |   
  if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
    echo $PATH
    clang++ --version
    ${TRAVIS_BUILD_DIR}/clang-windows/llvm+clang-10.0.0-win64-msvc-release/bin/clang++ --version
    cmake -G "Visual Studio 16 2019" -A x64 -T LLVM_v142 -DLLVM_PATH=${TRAVIS_BUILD_DIR}/clang-windows/llvm+clang-10.0.0-win64-msvc-release -DINSIGHTS_STATIC=Yes -DINSIGHTS_LLVM_CONFIG=${TRAVIS_BUILD_DIR}/clang-windows/llvm+clang-10.0.0-win64-msvc-release/bin/llvm-config.exe ..
    #${TRAVIS_BUILD_DIR}/scripts/travis_windows.bat
  else
    cmake -DINSIGHT_LLVM_CONFIG=${LLVM_CONFIG} ..
  fi

script:
- export TAG_NAME=$(git describe --exact-match)    
- cmake --build .
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      mv ${TRAVIS_BUILD_DIR}/build/travistest ${TRAVIS_BUILD_DIR}/build/travistest_osx
  fi
  
# deploy:
#   provider: releases
#   api_key:
#     secure: QnFBjBWMyn6A9Cs+cf8tDNyVmQkbig3YW6IfJcjsXQ57hMNTqrKOyvUMNAIxyxDL3sh5HrBAkeaVRI0uiGOwCQaigBg4tMEdjTZfiH9pNjKpbZli8OUB3I0LPMSmYkIZRQiN/A5BsuyFpXMCwMgg0wwSc8HgjZBuzBXMSlC26O8rXD62ZTT7ZKYGovOW5GX7UuxUTZ4UvUUycMajZjteuYQgnsXI8aNQaWO8pV7wuI2+ayHKvKVS6OSBzrlXkb74GIK37ltSjbNJbS31mpdd81NfJE7HQK9Kfqwrsr852uTEbeiZoe6sOT0CajaPpmkEUjR/WrCptXZuvtpNppQLQSTLLJXVRoUM8PyGAbtWGU+fTz4wFcvJgEBWKlwpSEqVr8KvPs4GzAJi4RfG8Q2Lwd86Xtdu/1S8mHJ5xTGO3FNw6xvrM5JVCg8g7rfrJGrBF8vCY+XE/YJKpXly3ZoPPPGx0lAyElvBveMQnyaMYvdI1BAGoosrKOAUPDDzUqptwWKb/g/DgUVyKS0srK12x9baFep7Vk693jcpAKmt5EKewFBcbJKdIlWWrp+5ZJvbOCeWjdn4DPc0WPNha+Mz5ahaCUm2AWml9a1KEAj0ApqD0UsrysNjzw0EloRwapTMXnWVwcMIF9ZFcmf7xkPfgl1qvYbJ6E9xxwEYnifAWNw=
#   file: ${TRAVIS_BUILD_DIR}/build/travistest
#   skip_cleanup: true
#   on:
#     repo: andreasfertig/travistest
#     branch: master
#     condition: $TRAVIS_OS_NAME = linux || $DEPLOY = Yes || -n $TAG_NAME
#     tags: true

# deploy:
#   provider: releases
#   api_key:
#     secure: QnFBjBWMyn6A9Cs+cf8tDNyVmQkbig3YW6IfJcjsXQ57hMNTqrKOyvUMNAIxyxDL3sh5HrBAkeaVRI0uiGOwCQaigBg4tMEdjTZfiH9pNjKpbZli8OUB3I0LPMSmYkIZRQiN/A5BsuyFpXMCwMgg0wwSc8HgjZBuzBXMSlC26O8rXD62ZTT7ZKYGovOW5GX7UuxUTZ4UvUUycMajZjteuYQgnsXI8aNQaWO8pV7wuI2+ayHKvKVS6OSBzrlXkb74GIK37ltSjbNJbS31mpdd81NfJE7HQK9Kfqwrsr852uTEbeiZoe6sOT0CajaPpmkEUjR/WrCptXZuvtpNppQLQSTLLJXVRoUM8PyGAbtWGU+fTz4wFcvJgEBWKlwpSEqVr8KvPs4GzAJi4RfG8Q2Lwd86Xtdu/1S8mHJ5xTGO3FNw6xvrM5JVCg8g7rfrJGrBF8vCY+XE/YJKpXly3ZoPPPGx0lAyElvBveMQnyaMYvdI1BAGoosrKOAUPDDzUqptwWKb/g/DgUVyKS0srK12x9baFep7Vk693jcpAKmt5EKewFBcbJKdIlWWrp+5ZJvbOCeWjdn4DPc0WPNha+Mz5ahaCUm2AWml9a1KEAj0ApqD0UsrysNjzw0EloRwapTMXnWVwcMIF9ZFcmf7xkPfgl1qvYbJ6E9xxwEYnifAWNw=
#   file: ${TRAVIS_BUILD_DIR}/build/travistest_osx
#   skip_cleanup: true
#   on:
#     repo: andreasfertig/travistest
#     branch: master
#     condition: $TRAVIS_OS_NAME = osx || -n $TAG_NAME
#     tags: true
